// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace StylesScssNamespace {
  export interface IStylesScss {
    productsActive: string;
    products_active: string;
  }
}

declare const StylesScssModule: StylesScssNamespace.IStylesScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesScssNamespace.IStylesScss;
};

export = StylesScssModule;
