const webpack = require('webpack');
const merge = require('webpack-merge');

const common = require('./webpack.common.js');

const plugins = [
  new webpack.DefinePlugin({
    'process.env.DEVELOPMENT': true,
  }),
];

const styleLoader = {
  test: /\.(s)?css$/,
  use: [
    'style-loader',
    {
      loader: '@teamsupercell/typings-for-css-modules-loader',
      options: {
        banner:
          '// autogenerated by typings-for-css-modules-loader. \n// Please do not change this file!',
        formatter: 'prettier',
      },
    },
    {
      loader: 'css-loader',
      options: {
        modules: {
          localIdentName: '[path][name]__[local]--[hash:base64:5]',
        },
        importLoaders: 1,
        sourceMap: true,
        localsConvention: 'camelCase',
      },
    },
  ],
};

module.exports = merge.smart(
  {
    mode: 'development',
    module: {
      rules: [styleLoader],
    },
    plugins,
    devtool: 'inline-source-map',
    devServer: {
      historyApiFallback: true,
      host: '0.0.0.0',
      port: process.env.WEBPACK_DEVSERVER_PORT || 3000,
      hot: true,
      compress: true,
    },
  },
  common,
);
